Update patch set 4
Patch Set 4: Code-Review+1

IIUC this unblocks breakage trying to deploy a new undercloud via oooq on current master so it would be nice to get this merged.  When oooq attempts to virt-customize the image for the overcloud it updates rpms and the update fails with the following error:

Error: Package: openstack-gnocchi-indexer-sqlalchemy-4.1.2-0.20171202174210.83d4e3c.el7.centos.noarch (@delorean)
           Requires: openstack-gnocchi-common = 4.1.2-0.20171202174210.83d4e3c.el7.centos
           Removing: openstack-gnocchi-common-4.1.2-0.20171202174210.83d4e3c.el7.centos.noarch (@delorean)
               openstack-gnocchi-common = 4.1.2-0.20171202174210.83d4e3c.el7.centos
           Updated By: openstack-gnocchi-common-4.1.2-0.20171222000340.79fb181.el7.centos.noarch (delorean)
               openstack-gnocchi-common = 4.1.2-0.20171222000340.79fb181.el7.centos

Patch-set: 4
Reviewer: Gerrit User 250 <250@270e2033-b340-4cff-9539-693957ebf0e7>
Label: Code-Review=+1